# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - kidneydisease

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://dlproject.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_9771c53e28694d1a80b4b9c9e3c8578d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7486f538ee10409e91399baba8370358 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: dlproject.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9771c53e28694d1a80b4b9c9e3c8578d }}/kidneydisease:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'kidneydisease'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5c350280fdc24c26aa2063faaf458328 }}
        images: 'dlproject.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9771c53e28694d1a80b4b9c9e3c8578d }}/kidneydisease:${{ github.sha }}'